services:
  sensor_agent:
    build: .
    container_name: sensor_agent_${CLIENT_NAME}
    network_mode: host
    restart: unless-stopped
    environment:
      - MASTER_URL=http://localhost:5000
      - SENSOR_ID=${SENSOR_ID}
      - CLIENT_NAME=${CLIENT_NAME}
      - SCAN_RANGE=${SCAN_RANGE}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  tunnel:
    image: kroniak/ssh-client:latest
    container_name: sensor_tunnel_${CLIENT_NAME}
    network_mode: host
    volumes:
      - "./ssh_keys:/root/.ssh:ro"
    command: >
      ssh -o StrictHostKeyChecking=no
      -o ExitOnForwardFailure=yes
      -o ServerAliveInterval=60
      -v
      -N -L 0.0.0.0:5000:localhost:5000
      scanner_user@${MASTER_IP} -p 2222 -i /root/.ssh/id_ed25519
    restart: always