services:
  redis:
    image: redis:alpine
    container_name: sensor_redis
    restart: always
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  sensor_app:
    build: .
    container_name: sensor_app
    working_dir: /app
    volumes:
      - ./:/app
    restart: unless-stopped

  tunnel:
    image: kroniak/ssh-client:latest
    container_name: sensor_tunnel
    volumes:
      - "./ssh_keys:/root/.ssh:ro"
    command: >
      ssh -o StrictHostKeyChecking=no
      -o ExitOnForwardFailure=yes
      -o ServerAliveInterval=60
      -v
      -N -R 0.0.0.0:9024:10.0.2.15:9391 scanner_user@10.0.2.15 -p 2222 -i /root/.ssh/id_ed25519
    restart: always

volumes:
  gvm_data: